### ISSUE TITLE
for DL images, docker-compose needs GPU support

### ISSUE THREAD

**Issue by gpho** [manifoldai/orbyter-cookiecutter#81]
for orbyter-dl-dev, the following lines need to be added to the develop service of `docker-compose.yml`:

```
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
```

see https://docs.docker.com/compose/gpu-support/
